// Expo config plugin: teach the generated Android project how to sign a
// release build.
//
// `android/` is regenerated by `expo prebuild` on every CI run and is
// gitignored, so there is no committed build.gradle to edit — the signing
// config has to be injected during prebuild, which is what this does.
//
// All the actual work is in ./releaseSigning.js, which is kept free of any
// dependency so the root vitest run can cover it without mobile/node_modules
// installed. This file is only the Expo binding, and runs solely under
// `expo prebuild`, where @expo/config-plugins is guaranteed present.

const { withAppBuildGradle } = require("@expo/config-plugins");
const { injectReleaseSigning } = require("./releaseSigning");

/** @type {import('@expo/config-plugins').ConfigPlugin} */
const withReleaseSigning = (config) =>
  withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== "groovy") {
      throw new Error(
        `withReleaseSigning: expected a Groovy build.gradle, got ${cfg.modResults.language}.`,
      );
    }
    cfg.modResults.contents = injectReleaseSigning(cfg.modResults.contents);
    return cfg;
  });

module.exports = withReleaseSigning;
