// Teaches the generated Android project how to sign a release build.
//
// `android/` is regenerated by `expo prebuild` on every CI run and is
// gitignored, so there is no committed build.gradle to edit — the signing
// config has to be injected during prebuild, which is what this config plugin
// does.
//
// The injected block is PROPERTY-GATED. Without `ARCADE_UPLOAD_STORE_FILE` on
// the Gradle command line the release build type keeps signing with the debug
// key, exactly as before this plugin existed. That matters for two reasons:
// the PR/CI `assembleDebug` leg needs no secrets, and a fork (which cannot read
// them) still builds.
//
// The edits are anchored to specific text in the Expo template. If the template
// moves and an anchor is not found we THROW rather than return the string
// unchanged — a silent no-op here would produce a debug-signed "release" APK,
// which Android would refuse to install over a properly signed one later.

const { withAppBuildGradle } = require("@expo/config-plugins");

const MARKER = "ARCADE_UPLOAD_STORE_FILE";

// Gradle, not Groovy-in-a-string-in-JS: keep this readable, it is the part a
// human debugs when a signing problem shows up.
const RELEASE_SIGNING_CONFIG = `
        release {
            // Supplied by CI via gradle.properties; absent for local and PR
            // builds, which then fall through to the debug key below.
            if (project.hasProperty('${MARKER}')) {
                storeFile file(${MARKER})
                storePassword ARCADE_UPLOAD_STORE_PASSWORD
                keyAlias ARCADE_UPLOAD_KEY_ALIAS
                keyPassword ARCADE_UPLOAD_KEY_PASSWORD
            }
        }`;

const RELEASE_SIGNING_CHOICE =
  `signingConfig project.hasProperty('${MARKER}') ` +
  `? signingConfigs.release : signingConfigs.debug`;

/**
 * Rewrite an Expo-generated `android/app/build.gradle` so the release build
 * type signs with a real keystore when one is supplied.
 *
 * Pure: string in, string out. Idempotent — running it over its own output
 * returns that output unchanged, because prebuild may run more than once.
 *
 * @param {string} gradle contents of android/app/build.gradle
 * @returns {string} the rewritten contents
 */
function injectReleaseSigning(gradle) {
  if (gradle.includes(MARKER)) return gradle;

  const configsAt = gradle.indexOf("signingConfigs {");
  if (configsAt === -1) {
    throw new Error(
      "withReleaseSigning: no `signingConfigs {` block in app/build.gradle. " +
        "The Expo template changed; update this plugin rather than shipping " +
        "a release APK signed with the debug key.",
    );
  }
  const afterConfigs = configsAt + "signingConfigs {".length;

  // The release build type must be located relative to `buildTypes {`: the
  // debug build type carries the same `signingConfig signingConfigs.debug`
  // line, and rewriting that one instead would be both wrong and invisible.
  const buildTypesAt = gradle.indexOf("buildTypes {", afterConfigs);
  if (buildTypesAt === -1) {
    throw new Error(
      "withReleaseSigning: no `buildTypes {` block after signingConfigs in " +
        "app/build.gradle. The Expo template changed; update this plugin.",
    );
  }
  const releaseAt = gradle.indexOf("release {", buildTypesAt);
  if (releaseAt === -1) {
    throw new Error(
      "withReleaseSigning: no `release {` build type in app/build.gradle. " +
        "The Expo template changed; update this plugin.",
    );
  }
  const debugSigningAt = gradle.indexOf(
    "signingConfig signingConfigs.debug",
    releaseAt,
  );
  if (debugSigningAt === -1) {
    throw new Error(
      "withReleaseSigning: the release build type does not sign with " +
        "signingConfigs.debug, so there is nothing to replace. The Expo " +
        "template changed; update this plugin.",
    );
  }

  // Apply the later edit first so the earlier one does not shift its index.
  const withChoice =
    gradle.slice(0, debugSigningAt) +
    RELEASE_SIGNING_CHOICE +
    gradle.slice(debugSigningAt + "signingConfig signingConfigs.debug".length);

  return (
    withChoice.slice(0, afterConfigs) +
    RELEASE_SIGNING_CONFIG +
    withChoice.slice(afterConfigs)
  );
}

/** @type {import('@expo/config-plugins').ConfigPlugin} */
const withReleaseSigning = (config) =>
  withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== "groovy") {
      throw new Error(
        `withReleaseSigning: expected a Groovy build.gradle, got ${cfg.modResults.language}.`,
      );
    }
    cfg.modResults.contents = injectReleaseSigning(cfg.modResults.contents);
    return cfg;
  });

module.exports = withReleaseSigning;
module.exports.injectReleaseSigning = injectReleaseSigning;
module.exports.MARKER = MARKER;
